### ISSUE TITLE
Red Main Menu

### ISSUE THREAD

**Issue by Afrocntrik** [grondag/canvas#100]
![image](https://user-images.githubusercontent.com/11052983/92315714-e1870f80-efb7-11ea-802a-d884e4efdd79.png)
Black screen on options 
![image](https://user-images.githubusercontent.com/11052983/92315716-f9f72a00-efb7-11ea-9cca-2da3ae302444.png)

**Comment by Afrocntrik** [comment]
I'm using a CyanideX's Unity resource pack but when fading from the Mojang the main menu is red as shown above

**Comment by Afrocntrik** [comment]
Latest Canvas update; Mod Menu:
![image](https://user-images.githubusercontent.com/11052983/92315735-522e2c00-efb8-11ea-9c72-663aaca34350.png)

**Comment by grondag** [comment]
That's an interesting one.  Just to confirm, this is build 927, correct?

**Comment by grondag** [comment]
Do you have AE2 installed by any chance? I get a similar problem with it in the mods folder. 

No idea *how* that could happen but it is.

**Comment by Afrocntrik** [comment]
Yeah I do, this is build 927 and thanks for responding so fast

**Comment by grondag** [comment]
Thank you for reporting the issue quickly. It’s surprising how long major defects can go unreported.  

I’m able to reproduce this reliably with vanilla texture pack. If I make it past the menu it runs normally for me. Same for you?

@shartte, I’m guessing this one is on my side. You’re probably referencing something in startup that instantiates one of my things sooner than it normally happens, and it is probably setting some GL state that needs to be cleaned up. 

I will try to track it down.  If you get defect reports send them here. Will let you know if it turns out to be your fault. 😜

**Comment by shartte** [comment]
Alright, yeah we got one already :-D

But let me know what we do. We _do_ inject into Bootstrap.register() to initialize our API, although I am unclear what we'd do in there that messes with anything rendering related hmmm.

**Comment by grondag** [comment]
This is fixed in build 929, which should be visible on CF in a few minutes. It can also be found in releases.

@shartte Cause here was as I expected.  You do some model inspection/transformation for cable busses during init - perhaps a little earlier than other mods - and this was causing Canvas to initialize and upload an information texture that conveys information about the SpriteAtlas to shaders.  This upload was setting some GL state that interfered with screen rendering after startup. (Not sure which state - it didn't matter for the fix.)

While the metadata for this texture is needed during model bake, the image doesn't have to be created and uploaded until rendering starts.  So this was fixed by deferring texture creation and upload until it is needed during the render loop.
