### ISSUE TITLE
[Suggestion] Colored light system

### ISSUE THREAD

**Issue by paulevsGitch** [grondag/canvas#214]
Hi, I know that this topic was active several times, and such kind of lighting is not in priority development, but I have a small working approach that I want to suggest for the Canvas. The most colored lights mods use point lights and a shader to render them, this causes issues with large amount of lights and have issues with "light leaking" when light can be seen threw wall. I suggest another approach - use voxel lighting system (like MC use) and pass the resulted color into the shaders with 3D textures. This actually works in my tests ([link](https://github.com/paulevsGitch/ColorfulFabric)) and I get a nice result even with the simple lighting algorithm (3x3x3 blocks around light source are filled with proper light). I think something like this but with better approach can be a good part of the Canvas.

My approach screenshots (lamps mod and BYG mod blocks):

![2021-03-03_00 07 16](https://user-images.githubusercontent.com/17707380/110177509-203a3d00-7e16-11eb-8a20-927265f19265.png)
![2021-03-04_22 08 42](https://user-images.githubusercontent.com/17707380/110177490-1adcf280-7e16-11eb-90b5-a8fb9a0c0ea2.png)

**Comment by grondag** [comment]
Thank you for your suggestion.  The rendering of colored lights will be controlled by the active pipeline configuration and shaders.  Pipeline authors will have much flexibility, including the option to not implement colored lights.  At least one of the pipelines that ships with Canvas will eventually support them.

Pipeline authors will be able to choose how lighting data is conveyed to the shaders: via vertex data, volume textures (as you seem to suggest),  or as light lists.  Perhaps other options will be devised.  There's been some interest from the community in helping to advance this feature, so it may come sooner rather than later.
