### ISSUE TITLE
Canvas crashes on load with NoSuchFieldError

### ISSUE THREAD

**Issue by Codasylph** [grondag/canvas#35]
Crash report: https://pastebin.com/Pyz5dukK (hastebin is not having it today, idkw)

It is entirely possible that I have included something wrong or otherwise messed up so for reference here's my build.gradle and gradle.properties: https://pastebin.com/qnKk6xjD

**Comment by grondag** [comment]
Your grade setup looks OK. I think it's happening because there was a change in Loom I didn't know about and the last build I pushed was de-obfuscated, and so Canvas isn't getting remapped.  I am using earlier yarn mappings 1.12.3 and apparently Direction.Axis.Y got renamed because reasons.

I should have new build up pretty soon and hopefully that fixes it.  If not, then it maybe a problem with Loom 2.2 vs 2.4, but probably not.

**Comment by Codasylph** [comment]
Yeah, i know that gradle says loom 2.2, but I tried it in my actual project as well (that was from a test project) and it uses 2.4 and gets the same error, so its probably the mapping issue because every time there's a new yarn build something gets its name changed. It's like angels getting their wings.

**Comment by grondag** [comment]
Confirmed this appears to be working in dev using 0.7.4+build.330

The problem was indeed caused by a de-obfuscated jar on my maven.
