### ISSUE TITLE
Memory leak under OpenJ9

### ISSUE THREAD

**Issue by Ristovski** [grondag/canvas#36]
Running Canvas under [OpenJ9-JDK11](https://www.eclipse.org/openj9/) (not to be confused with OpenJDK9) seems to be causing a gradual memory leak where a full client restart is required. 

What's even more interesting, is that RAM usage remains roughly the same (as reported by `htop`) - only `buff/cache` (indicated by `free -mh` under Linux) seems to go up. Thus, not only is a client restart required - but also freeing the buff/cache via `echo 3 > /proc/sys/vm/drop_caches`.

_This might be caused by virtual memory, but I am not sure._

I initially suspected OpenJ9s "JIT Compiler" threads, since those are the only ones that seem to be using any sort of disk I/O. But that would imply it would happen all the time - and it only happens with Canvas loaded.

Do note the whole `buff/cache` thing could be a side-effect of the high memory allocation and might as well be irrelevant.

Asking around Fabrics Discord, a user shared the following screenshot of OptiFines author explaining a similar issue with OpenJ9 (apparently /not/ OpenJDK9, as written in the screenshot) 
![image](https://user-images.githubusercontent.com/994445/61127159-b9347b80-a4ae-11e9-9de1-6def38d6c861.png)

Note how JDK9-12 are supposed to mitigate this, yet it happens with JDK11 anyways.

No idea if relevant or helpful, but going under water seems to accelerate the issue.

I will try and get more accurate RAM/VRAM measurements later today or tomorrow.

Any ideas on how to try debugging this?

**Comment by grondag** [comment]
Thank you for the excellent report.

Best guess is that it is caused by some incompatibility with LWJGL's [MemoryUtil](https://javadoc.lwjgl.org/org/lwjgl/system/MemoryUtil.html) allocation routines, which default to using Unsafe if available, then reflection if not. 

There is/was such a [bug with OpenJDK 9](https://bugs.openjdk.java.net/browse/JDK-8202113) which, as you point out, is not the same as OpenJ9.  But that does illustrate that such bugs are possible.

The biggest consumer in Canvas will be chunk buffer uploads, for which Canvas uses `MemoryUtil.memAlloc()` and `MemoryUtil.memFree()`.  It appears likely the calls could be made on different threads but they should be properly matched 1:1.  

The only other use of `memAlloc/memFree` is for light map texture initialization, but it 1X and likely not the culprit.

To reproduce this in isolation a simple test app that allocates and deallocates on multiple threads with a variety of buffer sizes might do the job.  I will eventually get around to doing that myself but if you want to have a go at it that would be great.

As for how to fix, I will probably be replacing those buffers with a pool of fixed-sized buffers for reuse, which may help, or perhaps LWJGL offers a different allocation routine that is more compatible (though perhaps less performant.) I have not done that research yet.

If the issue turns out to be allocate/release on different threads, I should be able to force both onto the client thread if necessary.

**Comment by grondag** [comment]
Also - a faster if less exact way to confirm the problem is the chunk buffer allocation:  just open a world and load a bunch of render chunks, either via F3+A or moving across terrain.  If the leak is worse when you do that, it is almost certainly a problem with the MemoryUtil routines.

**Comment by BrimsonBhin** [comment]
The memory leak is still present with AdoptOpenJDK's [**jdk-12.0.1+12_openj9-0.14.1**](https://adoptopenjdk.net/releases.html?variant=openjdk12&jvmVariant=openj9#x64_win)

The leak worsens as I move across terrain I did not previously visit in my current session.

**Comment by grondag** [comment]
That does help some. I need to confirm it doesn’t happen on other JVMs and then I can try a different allocation approach.

**Comment by Ristovski** [comment]
So I just tested spamming F3+A in a superflat world and I can confirm that with Canvas the RAM usage seems to go up over time (and especially `buff/cache`). 

So it indeed does seem like some of the allocations are not getting freed.

Both instances (with and without Canvas) started off at about ~850-900MB of RAM, the one _without_ Canvas stayed at that value most of the time while the one _with_ Canvas shot up to 1800MB fairly quickly.

The 'memory allocated' metric in the F3 debug screen stayed the same, along with the reported memory use. (Which I guess confirms the issue is with the `MemoryUtil` allocations.)

**Comment by BrimsonBhin** [comment]
Memory leak happens on Zulu's JRE 11, but does not happen on AdoptOpenJDK's JRE 12 with HotSpot

**Comment by grondag** [comment]
Thank you for the confirmation.  I'm focused on a different (not yet released) mod currently, but will get back to working on Canvas "soon."

**Comment by Ristovski** [comment]
@grondag any updates on this?

**Comment by grondag** [comment]
![2019-08-04_17 35 38](https://user-images.githubusercontent.com/6106235/62431692-61b8b280-b6de-11e9-9384-590617c9082d.png)

AdoptOpenJDK 12 with HotSpot is working great on OSX.  Guessing it is OS-specific.

**Comment by grondag** [comment]
Should hopefully be better in build 354, available now on Curse: https://www.curseforge.com/minecraft/mc-mods/canvas-renderer/files/2756313

I found some scenarios where it may not have been properly deallocating.  If that doesn't fix the problem, try enabling "safe memory allocation" on the debug config tab.  That will use NIO buffers which are much slower but they automatically deallocated via JVM garbage collection. 

Please let me know if the problem persists.

**Comment by Ristovski** [comment]
Just tested the new version and it's better! Memory usage still goes up over time though, albeit _much_ slower than before.

With NIO buffers, the memory usage is still a bit higher but doesn't seem to go up that much.

One thing I did notice when spamming F3+A in rapid succession, was that with Canvas the CPU usage goes up and FPS drops to ~19FPS, while without Canvas reloading chunks at that speed yields no FPS drop.

This happens both with default and NIO buffers. I don't recall this happening with previous versions, but I could be wrong and might test that out later.

**Comment by grondag** [comment]
It does do extra work now on chunk reload to ensure that all buffers are deallocated. When an early reload happens that way there can easily be a couple thousand buffers awaiting access to the main thread for upload, especially on a fast machine. Now it should block until they are all released
