### ISSUE TITLE
Canvas crashes upon enabling Faithful 32x

### ISSUE THREAD

**Issue by B055-Man** [grondag/canvas#398]
**System Information**

- Minecraft Version: 
- Canvas Version: 1.0.2487
- Operating System: Windows 11
- Graphics Card: 3060ti

**Other mods and versions installed**

- fabric api 0.62.0
- fabric loader 0.14.9
- newest version of faithful 32x

**How you triggered the behavior**

- start minecraft
- open options and enable faithful 32x
- click done

**What you expected would happen**

- The game would reload and the texture pack would be applied.

**What actually happened**

- The game crashed after reload. 

**Logs and screenshots**
- https://mclo.gs/vDeXJWE

**Extra**
- This occurs with canvas basic pipeline and forget-me-not. 
- Also tryed barebones resource pack and the game ran normally.
- faithfulpack.net
- https://github.com/Faithful-Resource-Pack/Faithful-Java-32x/issues/22

**Comment by grondag** [comment]
I've been able to reproduce a similar crash but it is not specific to Faithful 32x.  The game will load successfully with Faithful 32x.  The crash happens when changing resource packs while the world is loaded and appears to be intermittent.  For me it usually happens on the 1st or 2nd attempt to reload with a different texture resource pack.

**Comment by grondag** [comment]
This appears to have been corrected in https://github.com/vram-guild/canvas/commit/b47b1df8464ae46942668f4bb5c3e0974199f216
