### ISSUE TITLE
Crash occurs when using REI with Canvas Renderer

### ISSUE THREAD

**Issue by jac4e** [grondag/canvas#73]
**Description**
When accessing the inventory while using REI with Canvas renderer, it will crash. Crashes only seem to happen when a lot of items are shown by having a large window and small GUI scale, or when scrolling through pages with normal window size and GUI scale. I don't believe it is caused by how an item is rendered as manipulating the window to only show one column of items did not produce any crashes while scrolling through all the item pages.

**Reproduction steps**
The simplest way to reproduce:
1. Launch a Minecraft window with the size 1920x1080
2. Set GUI scale to 1
3. Load any world or server, does not matter
4. Open inventory when in the world

**Environment:**
 - Minecraft: [ 1.16.1 ]
 - Mod Loader: [ Fabric ]
 - Fabric API [ 0.17.0+build.386-1.16.1 ]
 - Canvas Renderer [ 1.0.871 ]
 - REI [ 4.12.0 ]

**Logs**

- [Crash Log](https://pastebin.com/h7Hg6NqE)
- [Client Log](https://pastebin.com/CVH1fBY7)

**Comment by grondag** [comment]
Closing to merge with #83.  Appears to be an Nvidia driver issue.  Some more suggestions on that issue. 

Having more items on the screen probably trigger the issue because it increases the odds it happens.  On OSX/AMD REI consistently renders with large numbers of items.

![2020-09-05_09 25 27](https://user-images.githubusercontent.com/6106235/92310029-42cec480-ef5f-11ea-92e9-5ed242c65fc0.png)
